### PR TITLE
Dynamic moving average

### PR DESCRIPTION
**Pull request by guilhermerc**
A moving average filter with dynamic order setting.

This core only supports orders which the number of taps of resulting FIR (order + 1) is a power of 2. The reason for that is so we can perfom divisions by simply shifting the fixed point to the left.

### CODE REVIEW

**Comment by guilhermerc** [comment]
Still need to improve testbench.

**Comment by guilhermerc** [comment]
@augustofg , testbench is finished. Can we merge this?

**Review by augustofg — CHANGES_REQUESTED** [review]
I think that the `.dat` files are excessive in size. 10000 values would be enough for me.

**Comment by guilhermerc** [comment]
> I think that the `.dat` files are excessive in size. 10000 values would be enough for me.

Test files were trimmed to 10000 samples.

**Pull request merged**
